<?php
    
    namespace Xmgr\Controllers\Request;
    
    /**
     * Class AbstractRequestController
     *
     * Represents an abstract request controller that handles a request.
     * Subclasses should implement the handle() method to perform necessary processing and generate a response.
     */
    abstract class AbstractRequestController {
        
        protected mixed  $handler;
        protected string $output = '';
        
        /**
         * Handles the given request.
         *
         * This method should be implemented by subclasses to handle the given request.
         * The implementation should perform any necessary processing, such as validating input,
         * performing actions, and generating a response.
         *
         * @return mixed The response generated by handling the request.
         * @throws \Throwable If an error occurs during handling of the request.
         */
        abstract public function handle();
        
        /**
         * Sends the data to the specified destination.
         *
         * This method is declared as abstract, so it needs to be implemented by the subclass.
         * The implementation should handle the specifics of sending the data to the destination.
         *
         * @return void
         */
        abstract public function send();
        
    }
